<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>EcDataguardAgent</AssemblyName>
    <RootNamespace>EcDataguard.Agent</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcDataguard.Agent.Core\EcDataguard.Agent.Core.csproj" />
  </ItemGroup>

</Project>