<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>EcDataguardAgent7</AssemblyName>
    <RootNamespace>EcDataguard.Agent</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcDataguard.Agent.Core\EcDataguard.Agent.Core.csproj" />
  </ItemGroup>

</Project>